vim.g.copilot_filetypes = {
    ["*"] = false,
    markdown = true,
    javascript = true,
    typescript = true,
    typescriptreact = true,
    javascriptreact = true,
    lua = true,
    python = true,
    gitignore = true,
    latex = true,
    tex = true,
    r = true,
    R = true,
    sh = true,
    php = true,
    js = true,
}
