require("0_11.config.remap")
require("0_11.config.settings")
require("0_11.config.copilot")
require("0_11.config.lsp.lsps")
require("0_11.config.my_attach")
require("0_11.config.lazy_init")
print("hello from 0_9")
